class Emoji {
  static const level1 = [
    {'name': 'hand', 'emoji': '✋'},
    {'name': 'mouse', 'emoji': '🖱'},
    {'name': 'plug', 'emoji': '🔌'},
    {'name': 'light bulb', 'emoji': '💡'},
    {'name': 'book', 'emoji': '📚'},
    {'name': 'cellphone', 'emoji': '📱'},
    {'name': 'keyboard', 'emoji': '⌨️'},
    {'name': 'tv', 'emoji': '📺'},
    {'name': 'laptop', 'emoji': '💻'},
    {'name': 'shirt', 'emoji': '👕'},
    {'name': 'pants', 'emoji': '👖'},
    {'name': 'shoe', 'emoji': '👞'}
  ];

  static const level2 = [
    {'name': 'key', 'emoji': '🔑'},
    {'name': 'newspaper', 'emoji': '📰'},
    {'name': 'plate', 'emoji': '🍽'},
    {'name': 'sock', 'emoji': '🧦'},
    {'name': 'coat', 'emoji': '🧥'},
    {'name': 'wallet', 'emoji': '👛'},
    {'name': 'bed', 'emoji': '🛏'},
    {'name': 'cup', 'emoji': '☕'},
    {'name': 'watch', 'emoji': '⌚'},
    {'name': 'trash can', 'emoji': '🗑'},
    {'name': 'envelope', 'emoji': '✉️'},
    {'name': 'sunglasses', 'emoji': '🕶'},
    {'name': 'toilet', 'emoji': '🚽'},
    {'name': 'clock', 'emoji': '🕑'},
    {'name': 'hat', 'emoji': '🧢'},
    {'name': 'backpack', 'emoji': '🎒'},
    {'name': 'headphones', 'emoji': '🎧'},
    {'name': 'display', 'emoji': '🖥'},
    {'name': 'spoon', 'emoji': '🥄'},
    {'name': 'bowl', 'emoji': '🥣'}
  ];

  static const level3 = [
    {'name': 'scarf', 'emoji': '🧣'},
    {'name': 'scissors', 'emoji': '✂️'},
    {'name': 'cabinet', 'emoji': '🗄'},
    {'name': 'tree', 'emoji': '🌲'},
    {'name': 'beer', 'emoji': '🍺'},
    {'name': 'sofa', 'emoji': '🛋'},
    {'name': 'house', 'emoji': '🏠'},
    {'name': 'building', 'emoji': '🏢'},
    {'name': 'bicycle', 'emoji': '🚲'},
    {'name': 'frying pan', 'emoji': '🍳'},
    {'name': 'wine', 'emoji': '🍷'},
    {'name': 'bread', 'emoji': '🍞'},
    {'name': 'printer', 'emoji': '🖨'},
    {'name': 'banana', 'emoji': '🍌'},
    {'name': 'car', 'emoji': '🚗'},
    {'name': 'flower', 'emoji': '🌼'},
    {'name': 'glove', 'emoji': '🧤'},
    {'name': 'umbrella', 'emoji': '☂️'},
    {'name': 'bathtub', 'emoji': '🛁'},
    {'name': 'camera', 'emoji': '📷'}
  ];

  static const level4 = [
    {'name': 'cat', 'emoji': '🐱'},
    {'name': 'guitar', 'emoji': '🎸'},
    {'name': 'dog', 'emoji': '🐶'},
    {'name': 'orange', 'emoji': '🍊'},
    {'name': 'strawberry', 'emoji': '🍓'},
    {'name': 'piano', 'emoji': '🎹'},
    {'name': 'hammer', 'emoji': '🔨'},
    {'name': 'microphone', 'emoji': '🎤'},
    {'name': 'broccoli', 'emoji': '🥦'},
    {'name': 'lipstick', 'emoji': '💄'},
    {'name': 'lock', 'emoji': '🔒'},
    {'name': 'mailbox', 'emoji': '📪'},
    {'name': 'soccer ball', 'emoji': '⚽'},
    {'name': 'mushroom', 'emoji': '🍄'},
    {'name': 'lemon', 'emoji': '🍋'},
    {'name': 'baseball', 'emoji': '⚾'},
    {'name': 'basketball', 'emoji': '🏀'},
    {'name': 'flashlight', 'emoji': '🔦'},
    {'name': 'candle', 'emoji': '🕯'},
    {'name': 'radio', 'emoji': '📻'}
  ];

  static const level5 = [
    {'name': 'fish', 'emoji': '🐟'},
    {'name': 'icecream', 'emoji': '🍨'},
    {'name': 'pizza', 'emoji': '🍕'},
    {'name': 'bird', 'emoji': '🐦'},
    {'name': 'cassette', 'emoji': '📼'},
    {'name': 'hamburger', 'emoji': '🍔'},
    {'name': 'hotdog', 'emoji': '🌭'},
    {'name': 'fries', 'emoji': '🍟'},
    {'name': 'ramen', 'emoji': '🍜'},
    {'name': 'donut', 'emoji': '🍩'},
    {'name': 'sushi', 'emoji': '🍣'},
    {'name': 'taco', 'emoji': '🌮'},
    {'name': 'burrito', 'emoji': '🌯'},
    {'name': 'traffic light', 'emoji': '🚦'},
    {'name': 'bus', 'emoji': '🚎'},
    {'name': 'truck', 'emoji': '🚚'},
    {'name': 'screw', 'emoji': '🔩'},
    {'name': 'sax', 'emoji': '🎷'},
    {'name': 'baby bottle', 'emoji': '🍼'},
    {'name': 'motor scooter', 'emoji': '🛵'},
    {'name': 'magnifying glass', 'emoji': '🔎'},
    {'name': 'jack o lantern', 'emoji': '🎃'}
  ];
}
